# Reference: https://skaffold.dev/docs/references/yaml/
#
# TODO(jlewi): This is just a rudimentary skaffold config.
# Users probably need to create their own profile based on the resources (e.g. GCR)
# They have access too.
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: codeserver-web-app
build:
  artifacts:
  - image: brightfly/codeserver-web-app
    # Context should be ${KUBEFLOW_REPO}/components
    context: .
    kaniko:
      dockerfile: Dockerfile
      buildContext:
        localDir: {}
      cache: {}
  cluster:
    namespace: default
    dockerConfig:
      secretName: skaffold-cfg

